spring:
  application:
    name: notification-server

  datasource:
    url: jdbc:postgresql://localhost:5432/mail
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      default_schema: app
    open-in-view: false

  liquibase:
    liquibase-schema: app

  mail:
    host:  ${ENV_MAIL_HOST:smtp.mail.ru}
    port: ${ENV_MAIL_PORT:465}
    username: ${ENV_MAIL_USERNAME:genia-genius-91@mail.ru}
    password: ${ENV_MAIL_PASSWORD:6Pp2xaceETZ57gM9hkx8}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  kafka:
    consumer:
      group-id: notification-event
      bootstrap-servers: localhost:9092, localhost:9094
      isolation-level: READ_COMMITTED
      properties:
        spring:
          json:
            trusted:
              packages: by.it_academy.*

  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    property-naming-strategy: SNAKE_CASE

topic:
  name:
    code-created-topic: code-created-topic
    register-completed-topic: register-completed-topic

scheduler:
  period: 1