name: finance-app

services:
  proxy:
    build: proxy
    image: proxy-finance:1.0.0
    ports:
      - 80:80
    networks:
      - finance-network

  user-service:
    build: user-service
    image: user-service:1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - finance-db
    networks:
      - finance-network
    ports:
      - 8085:8080

  classifier-service:
    build: classifier-service
    image: classifier-service:1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - finance-db
    networks:
      - finance-network
    ports:
      - 8081:8080

  audit-service:
    build: audit-service
    image: audit-service:1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - finance-db
    networks:
      - finance-network
    ports:
      - 8083:8080

  account-service:
    build: account-service
    image: account-service:1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - finance-db
    networks:
      - finance-network
    ports:
      - 8082:8080

  finance-db:
    build: postgresql
    image: postgresql-finance:1.0.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - finance-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finance.com
      PGADMIN_DEFAULT_PASSWORD: finance
    ports:
      - 82:80
    networks:
      - finance-network

networks:
  finance-network: