org:
  quartz:
    jobStore:
      tablePrefix: QRTZ_
      isClustered: true
      driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate



spring:
  application:
    name: scheduler-service
  datasource:
    url: jdbc:postgresql://192.168.100.13:5432/scheduler
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    liquibase-schema: public
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      default_schema: app
    open-in-view: false
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    property-naming-strategy: SNAKE_CASE

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: QuartzScheduler
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            tablePrefix: QRTZ_
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 1
            threadsInheritContextClassLoaderOfInitializingThread: true

logging:
  level:
    root: info
    org.springframework.jdbc.core: trace
  file:
    name: finance.log
    path: /

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
