spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:postgresql://192.168.100.13:5432/audit
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    liquibase-schema: public               #???? ? ?????? ????? ???
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      default_schema: app
    open-in-view: false
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    root: info
    #    com.dmdev.spring.database.pool: info
    org.springframework.jdbc.core: trace
  file:
    name: finance.log
    path: /

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw