spring:
  datasource:
    url: jdbc:postgresql://finance-db:5432/audit
    username: postgres
    password: root                       #может поменяется
#  liquibase:
#    liquibase-schema: public               #пока в паблик схему ???