spring:
  application:
    name: classifier-service
  boot:
    admin:
      client:
        #        username: admin
        #        password: admin
        url: http://localhost:8080
        instance:
          service-base-url: http://localhost:8081
#  cloud:
#    vault:
#      uri: http://192.168.100.42:32768
#      token: root
#      config:
#        lifecycle:
#          enabled: true
#      kv:
#        enabled: true
#        backend: secret
#  config:
#    import: vault://, optional:file:.env
  datasource:
    url: jdbc:postgresql://192.168.100.13:5432/classifier
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    liquibase-schema: public
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      default_schema: app
    open-in-view: false
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: info
    org.springframework.jdbc.core: trace
  file:
    name: finance.log
    path: /

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw

api:
  access:
    key: 3abfa1ddd7a647cd88d13c645584d0a4
    url: https://api.exchangerate.host