logging:
  level:
    root: info
#    com.dmdev.spring.database.pool: info
    org.springframework.jdbc.core: trace
  file:
    name: dmdev.log
    path: /
spring:
  application:
    name: classifier-service
  datasource:
    url: jdbc:postgresql://192.168.100.13:5432/classifier
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    liquibase-schema: public               #пока в паблик схему ???
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      default_schema: app
    open-in-view: false
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw