spring:
  datasource:
    url: jdbc:postgresql://finance-db:5432/classifier
    username: postgres
    password: root                       #может поменяется
#  liquibase:
#    liquibase-schema: app               #пока в паблик схему ???