scheduler:
  period: 3

spring:
  datasource:
    url: jdbc:postgresql://192.168.100.13/user
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      default_schema: app
    open-in-view: false
  liquibase:
    liquibase-schema: app               #пока в одну схему ???
  mail:
    host: ${ENV_MAIL_HOST:smtp.mail.ru}
    port: ${ENV_MAIL_PORT:465}
    username: ${ENV_MAIL_USERNAME:genia-genius-91@mail.ru}
    password: ${ENV_MAIL_PASSWORD:6Pp2xaceETZ57gM9hkx8}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  task:
    scheduling:
      pool:
        size: 3
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: info
    #    by.it_academy.jd2: debug
    org.springframework.jdbc.core: trace
  file:
    name: finance.log
    path: /

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    issuer: ITAcademy
    expiration: 7