spring:
  datasource:
    url: jdbc:postgresql://finance-db/user
    username: postgres
    password: root
  liquibase:
    liquibase-schema: app                # может в public закинуть

service:
  audit: audit-service:8080