management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  metrics:
    enable:
      all: true

spring:
  kafka:
    bootstrap-servers: kafka-1:9090, kafka-2:9090, kafka-3:9090

  boot:
    admin:
      client:
        url: http://admin-server:8080
        instance:
          service-base-url: http://user-service:8080
  datasource:
    url: jdbc:postgresql://finance-db:5432/user
    username: postgres
    password: root
  liquibase:
    liquibase-schema: app

service:
  audit: audit-service:8080