spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://192.168.100.13:5432/account
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      default_schema: app
    open-in-view: false
  liquibase:
    liquibase-schema: public               #пока в паблик схему ???
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false

logging:
  level:
    root: info
    #    com.dmdev.spring.database.pool: info
    org.springframework.jdbc.core: trace
  file:
    name: finance.log
    path: /

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw