spring:
  datasource:
    url: jdbc:postgresql://finance-db:5432/account
    username: postgres
    password: root
  liquibase:
    liquibase-schema: app               #пока в паблик схему ???

service:
  classifier: classifier-service:8080
  audit: audit-service:8080